name: ticket_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  geojson_vi: ^2.2.5
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  http: ^1.2.2
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  cupertino_icons: ^1.0.8
  envied: ^1.0.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  lottie: ^3.2.0
  share_plus: ^10.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  freezed: ^2.5.8
  riverpod_generator: ^2.6.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/geodata/prefectures.geojson
    - assets/geodata/hokkaido.geojson
    - assets/geodata/tohoku.geojson
    - assets/geodata/kanto.geojson
    - assets/geodata/chubu.geojson
    - assets/geodata/kinki.geojson
    - assets/geodata/chugoku.geojson
    - assets/geodata/shikoku.geojson
    - assets/geodata/kyushu.geojson
    - assets/geodata/okinawa.geojson
    - assets/animations/loadingAnimation.json
    - assets/animations/splash_screen.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_icons: 
  image_path_android: assets/icons/android_icon.png
  adaptive_icon_background: '#000000' #iconの背景色
  adaptive_icon_foreground: assets/icons/android_icon.png
  image_path_ios: assets/icons/ios_icon.png
  android: true
  adaptive_icon_padding: true
  min_sdk_android: 21 #Androidの最小SDKバージョン
  ios: true 

flutter_native_splash: 
  background_image: "assets/splash/splash_background.png"  #背景画像を指定
  image: "assets/splash/splash.png"  #スプラッシュ画像を指定
  android_12: 
    icon_background_color: "#000000"  #Android12用の背景色指定　#TODO: android12の背景色設定する
    image: "assets/splash/splash_android12.png"  #Android12用のスプラッシュ画像を指定
  android: true
  ios: true
  fullscreen: true  #trueで通知バーが非表示になる 
